In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

In [2]:
#load in bookclub dataset
df = pd.read_csv("bookclub.csv", error_bad_lines = False)

In [3]:
#load in good reads dataset
df2 = pd.read_csv("good_reads_final.csv")

In [4]:
#change the name of the author field for merging
df2["Author"] = df2["author_name"]
shape = df2.shape

In [5]:
df.columns

Index(['Chooser', 'author_average_rating', 'author_gender', 'author_genres',
       'birthplace', 'our_rating', 'book_average_rating', 'Title', 'genre_1',
       'genre_2', 'pages', 'publish_date', 'Author'],
      dtype='object')

In [6]:
# remove unfilled columns, for now
df6 = df.copy()
df6 = df6.drop(['our_rating'], axis = 1)
list = [0,5,7,12]
df = df.iloc[:,list]
df2 = df2.iloc[0:22891,:]

In [7]:
df6.head()

,Chooser,author_average_rating,author_gender,author_genres,birthplace,book_average_rating,Title,genre_1,genre_2,pages,publish_date,Author
0,Chris,4.14,female,literature-fiction,United Kingdom,4.00,Interpreter of Maladies,Short Stories,Fiction,198.0,4/20/1999,Jhumpa Lahiri
1,Schmidt,4.08,male,memior,United States,3.90,One Summer,History,Non-fiction,456.0,10/1/2013,Bill Bryson
2,Eric,4.18,male,literature-fiction,United States,NaN,A River Runs Through it and Other Stories,Fiction,Short Stories,217.0,1/1/1976,Norman Maclean
3,Emily,NaN,NaN,NaN,NaN,NaN,Reading Lolita in Tehran: A Memoir in Books,NaN,NaN,NaN,NaN,Azar Nafisi
4,David,3.81,male,literature-fiction,Ireland,3.81,Transatlantic,fiction,historical fiction,304.0,6/4/2013,Colum McCann

In [8]:
df6 = df6.dropna(subset=['book_average_rating'])
df6 = df6.dropna(axis='columns')
df6 = df6.drop(["Chooser", ], axis = 1)
df6

,author_average_rating,author_gender,author_genres,birthplace,book_average_rating,Title,genre_1,genre_2,pages,publish_date,Author
0,4.14,female,literature-fiction,United Kingdom,4.00,Interpreter of Maladies,Short Stories,Fiction,198.0,4/20/1999,Jhumpa Lahiri
1,4.08,male,memior,United States,3.90,One Summer,History,Non-fiction,456.0,10/1/2013,Bill Bryson
4,3.81,male,literature-fiction,Ireland,3.81,Transatlantic,fiction,historical fiction,304.0,6/4/2013,Colum McCann
6,3.84,male,literature-fiction,United States,3.84,The Log from The Sea of Cortez,nonfiction,classics,288.0,1/1/1951,John Steinbeck
7,4.13,male,literature-fiction,United States,4.13,Constellation of Vital Phenomena,fiction,historical fiction,416.0,2/4/2014,Anthony Marra
8,3.90,male,literature-fiction,United States,3.90,Lexicon,fiction,science fiction,390.0,6/8/2013,Max Berry
12,3.69,male,literature-fiction,United Kingdom,3.69,Quarantine,fiction,historical fiction,256.0,6/1/1997,Jim Crace
13,3.51,female,literature-fiction,United Kingdom,3.51,As She Left It,Mystery,Thriller,343.0,6/8/2013,Catriona Mcpherson
19,4.20,male,literature-fiction,United States,4.28,Ready Player One,science fiction,fiction,374.0,8/16/2011,Ernest Cline
23,3.64,female,literature-fiction,United States,3.64,The Turner House,fiction,african american,341.0,4/14/2015,Angela Flournoy
28,3.90,female,literature-fiction,United States,3.93,The Round House,fiction,mystery,323.0,10/2/2012,Louise Erdrich
34,4.13,female,nonfiction,Mexico,4.23,The Distance Between Us,nonfiction,autobiography,336.0,4/28/2012,Reyna Grande
37,3.84,female,fiction,United States,3.85,Z: a novel of Zelda Fitzgerald,historical fiction,fiction,464.0,3/26/2013,Therese Anne Fowler
41,3.93,female,literature-fiction,United States,3.86,Where I was from,nonfiction,autobiography,240.0,9/14/2004,Joan Didion
42,3.70,female,literature-fiction,United States,3.89,Caramelo,fiction,historical fiction,441.0,9/9/2003,Sandra Cisneros
44,3.90,female,literature-fiction,United States,3.54,The Future Home of the Living God,fiction,dystopia,263.0,11/14/2017,Louise Erdrich
48,3.64,male,literature-fiction,China,3.64,Balzac and the Little Chinese Seamstress,fiction,historical fiction,184.0,10/29/2002,Dai Sijie
50,4.03,male,horror,United States,3.96,The Gunslinger,fantasy,fiction,231.0,6/1/1982,Stephen King
51,3.64,male,literature-fiction,United States,3.60,The Family Fang,fiction,humor,320.0,8/1/2011,Kevin Wilson

In [9]:
# preview list of columns and datatypes
df2.dtypes

author average rating    float64
author gender             object
author genres             object
author id                float64
author name               object
author_name               object
author rating count      float64
author review count      float64
birthplace                object
book average rating      float64
book fullurl              object
book id                   object
Title                     object
book title                object
genre 1                   object
genre 2                   object
num ratings              float64
num reviews              float64
pages                     object
publish date              object
score                    float64
Author                    object
dtype: object

In [10]:
#summary statistics on the good reads dataset
df2.describe()

,author average rating,author id,author rating count,author review count,book average rating,num ratings,num reviews,score
count,22891.000000,2.289100e+04,2.289100e+04,22891.000000,22891.000000,2.289100e+04,22891.000000,22891.000000
mean,3.960368,3.233957e+06,1.720319e+05,9369.795640,3.951456,4.668349e+04,2324.754794,3893.028483
std,0.240421,3.868091e+06,6.546902e+05,24949.832609,0.291317,1.800698e+05,6837.503574,11022.018268
min,1.820000,4.000000e+00,6.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,55.000000
25%,3.810000,4.083550e+04,4.324500e+03,545.000000,3.770000,8.200000e+02,106.000000,832.000000
50%,3.970000,1.415543e+06,2.463500e+04,2273.000000,3.960000,4.403000e+03,384.000000,1727.000000
75%,4.120000,5.775601e+06,1.113370e+05,8262.500000,4.140000,2.014300e+04,1504.000000,3597.500000
max,5.000000,1.877045e+07,2.111732e+07,516745.000000,5.000000,3.820921e+06,147696.000000,598270.000000

In [11]:
#summary statistics on the book club dataset
df.describe()

       our_rating
count    53.00000
mean      2.80434
std       1.56937
min       0.00000
25%       2.00000
50%       3.00000
75%       3.90000
max       5.00000

In [12]:
#clean up the the author genres category and just select the first genre
df2 = df2.replace(r'\n',' ', regex=True) 
genres = df2["author genres"].str.rsplit(",", n=2, expand=True)
df2["author genres"] = genres[0]

df['book_average_rating'] = df['our_rating'].copy()
df = df.drop(['our_rating'],axis = 1)

In [13]:
#sort out really long books
#df2 = df2.loc[df2["pages"] != "1 page"]
#df2["pages"] = pd.to_numeric(df2["pages"])
#df2 = df2.loc[df2["pages"] <= 600]
#df2["pages"].head()

In [14]:
donna =df2.loc[df2["Title"] == "The Goldfinch"]
donna

,author average rating,author gender,author genres,author id,author name,author_name,author rating count,author review count,birthplace,book average rating,...,Title,book title,genre 1,genre 2,num ratings,num reviews,pages,publish date,score,Author
7469,3.93,female,fiction,8719.0,Donna Tartt,Donna Tartt,832715.0,70777.0,United States,3.89,...,The Goldfinch,The Goldfinch,Fiction,Contemporary,555283.0,49442.0,771,September 23rd 2013,8775.0,Donna Tartt
11936,3.93,female,fiction,8719.0,Donna Tartt,Donna Tartt,832715.0,70777.0,United States,3.89,...,The Goldfinch,The Goldfinch,Fiction,Contemporary,555283.0,49442.0,771,September 23rd 2013,3891.0,Donna Tartt

In [15]:
sorrows =df2.loc[df2["Title"] == "All My Puny Sorrows"]
sorrows

,author average rating,author gender,author genres,author id,author name,author_name,author rating count,author review count,birthplace,book average rating,...,Title,book title,genre 1,genre 2,num ratings,num reviews,pages,publish date,score,Author
12473,3.75,female,literature-fiction,8359.0,Miriam Toews,Miriam Toews,51853.0,5291.0,Canada,3.94,...,All My Puny Sorrows,All My Puny Sorrows,Fiction,Cultural,16433.0,2231.0,321,2014,2330.0,Miriam Toews
22513,3.75,female,literature-fiction,8359.0,Miriam Toews,Miriam Toews,51904.0,5298.0,Canada,3.94,...,All My Puny Sorrows,All My Puny Sorrows,Fiction,Cultural,16440.0,2231.0,321,2014,1344.0,Miriam Toews

In [16]:
df2 = df2.sort_values(by="score")
df2 =df2.drop_duplicates(subset='book id', keep="last")

In [17]:
df2.shape

(16830, 22)

In [18]:
# let's use donna tartt to make sure she is til
donna =df2.loc[df2["Author"] == "Donna Tartt"]
donna

,author average rating,author gender,author genres,author id,author name,author_name,author rating count,author review count,birthplace,book average rating,...,Title,book title,genre 1,genre 2,num ratings,num reviews,pages,publish date,score,Author
7469,3.93,female,fiction,8719.0,Donna Tartt,Donna Tartt,832715.0,70777.0,United States,3.89,...,The Goldfinch,The Goldfinch,Fiction,Contemporary,555283.0,49442.0,771,September 23rd 2013,8775.0,Donna Tartt
1512,3.93,female,fiction,8719.0,Donna Tartt,Donna Tartt,832587.0,70769.0,United States,4.09,...,The Secret History,The Secret History,Fiction,Mystery,231413.0,16453.0,559,1992,13335.0,Donna Tartt

In [19]:
df3 = df2.copy()
df3 = df3.drop(["author id", "author_name", "author name",  "author rating count", "author review count", "book title", "book fullurl", "num ratings", "num reviews", "book id", "score"], axis = 1)

In [20]:
df6.columns

Index(['author_average_rating', 'author_gender', 'author_genres', 'birthplace',
       'book_average_rating', 'Title', 'genre_1', 'genre_2', 'pages',
       'publish_date', 'Author'],
      dtype='object')

In [21]:
df3.columns = df6.columns
df3 = df3.append(df6, ignore_index = True)
df3 = df3.drop(["birthplace"], axis = 1)

In [22]:
df5 =pd.merge(df, df3, how='left', on=["Author", "Title"], 
         suffixes=('_x', '_y'),  indicator=False,
         validate=None)

In [23]:
df5 =df5.drop(['book_average_rating_y'], axis = 1)
df5['book_average_rating'] =  df5['book_average_rating_x']
df5 =df5.drop(['book_average_rating_x'], axis = 1)

In [24]:
text = df3["genre_1"].values
words = text.tolist()
words = [word.lower() for word in text]
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
stemmed = [porter.stem(word) for word in words]
df3.insert(10, "Genre1_Stemmed", stemmed, True)

In [25]:
text = df5["genre_1"].values
words = text.tolist()
words = [word.lower() for word in text]
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
stemmed = [porter.stem(word) for word in words]
df5.insert(10, "Genre1_Stemmed", stemmed, True)

In [26]:
text = df3["genre_2"].values
words = text.tolist()
words = [word.lower() for word in text]

from nltk.stem.porter import PorterStemmer

porter = PorterStemmer()
stemmed = [porter.stem(word) for word in words]
df3.insert(11, "Genre2_Stemmed", stemmed, True)

In [27]:
text = df5["genre_2"].values
words = text.tolist()
words = [word.lower() for word in text]

from nltk.stem.porter import PorterStemmer

porter = PorterStemmer()
stemmed = [porter.stem(word) for word in words]
df5.insert(11, "Genre2_Stemmed", stemmed, True)

In [28]:
text = df3["author_genres"].values
words = text.tolist()
words = [word.lower() for word in text]

from nltk.stem.porter import PorterStemmer

porter = PorterStemmer()
stemmed = [porter.stem(word) for word in words]
df3.insert(12, "authorgenre_stemmed", stemmed, True)

In [29]:
text = df5["author_genres"].values
words = text.tolist()
words = [word.lower() for word in text]

from nltk.stem.porter import PorterStemmer

porter = PorterStemmer()
stemmed = [porter.stem(word) for word in words]
df5.insert(12, "authorgenre_stemmed", stemmed, True)

In [30]:
df3.publish_date.unique().shape

(3339,)

In [31]:
porter.stem('running')

'run'

In [32]:
chooser_df = df5.copy()
df5 = df5.drop(['Chooser'], axis = 1)

In [33]:
df3.columns

Index(['author_average_rating', 'author_gender', 'author_genres',
       'book_average_rating', 'Title', 'genre_1', 'genre_2', 'pages',
       'publish_date', 'Author', 'Genre1_Stemmed', 'Genre2_Stemmed',
       'authorgenre_stemmed'],
      dtype='object')

In [34]:
df5 = df5[['book_average_rating', 'author_gender', 'author_genres',
       'author_average_rating', 'Title', 'genre_1', 'genre_2', 'pages',
       'publish_date', 'Author', 'Genre1_Stemmed', 'Genre2_Stemmed',
       'authorgenre_stemmed']]

In [35]:
df5.head()

,book_average_rating,author_gender,author_genres,author_average_rating,Title,genre_1,genre_2,pages,publish_date,Author,Genre1_Stemmed,Genre2_Stemmed,authorgenre_stemmed
0,4.0,female,literature-fiction,4.14,Interpreter of Maladies,Short Stories,Fiction,198,4/20/1999,Jhumpa Lahiri,short stori,fiction,literature-fict
1,3.9,male,memior,4.08,One Summer,History,Non-fiction,456,10/1/2013,Bill Bryson,histori,non-fict,memior
2,2.5,male,literature-fiction,4.16,A River Runs Through it and Other Stories,Fiction,Short Stories,217,1976,Norman Maclean,fiction,short stori,literature-fict
3,3.5,male,nonfiction,3.62,Reading Lolita in Tehran: A Memoir in Books,Nonfiction,Autobiography,356,March 25th 2003,Azar Nafisi,nonfict,autobiographi,nonfict
4,4.0,male,literature-fiction,3.81,Transatlantic,fiction,historical fiction,304,6/4/2013,Colum McCann,fiction,historical fict,literature-fict

In [36]:
df3 = df3.loc[df3.publish_date != "by"]
df3 = df3.loc[df3.publish_date != '0']
df3 = df3.dropna(subset=['publish_date'])

In [37]:
df3 = df3.drop([1224, 3600, 3909, 4130, 8176, 11170,12779,13187,13538,14929,15074])

In [38]:

import datetime
import dateutil.parser as dparser


for i in range(0,len(df3)):
    df3.iloc[i,8] = dparser.parse(df3.iloc[i,8],fuzzy=True).date()

In [39]:
df5.shape

(53, 13)

In [40]:
for i in range(0,len(df5)):
    df5.iloc[i,8] = dparser.parse(df5.iloc[i,8],fuzzy=True).date()

In [41]:
df5['dat_category'] = df5['publish_date'].copy()
for i in range(0, len(df5.publish_date)):
    if df5.iloc[i,8] > datetime.date(2018, 12, 31):
        df5.iloc[i,13] = 'hardcover only'
    elif (df5.iloc[i,8] <= datetime.date(2018, 12, 31) and df5.iloc[i,8] > datetime.date(2015, 1, 1)):
        df5.iloc[i,13] = 'within bookclub'
    elif (df5.iloc[i,8] <= datetime.date(2015, 1, 1) and df5.iloc[i,8] > datetime.date(2006, 8, 1)):
        df5.iloc[i,13] = 'college books'
    elif (df5.iloc[i,8] <= datetime.date(2006, 8, 1) and df5.iloc[i,8] >= datetime.date(2000, 1, 1)):
        df5.iloc[i,13] = 'early aughts'
    elif (df5.iloc[i,8] < datetime.date(2000, 1, 1) and df5.iloc[i,8] >= datetime.date(1990, 1, 1)):
        df5.iloc[i,13] = 'nineties' 
    elif (df5.iloc[i,8] < datetime.date(1990, 1, 1) and df5.iloc[i,8] >= datetime.date(1970, 1, 1)):
        df5.iloc[i,13] = 'seventies-eighties' 
    elif (df5.iloc[i,8] < datetime.date(1970, 1, 1) and df5.iloc[i,8] >= datetime.date(1960, 1, 1)):
        df5.iloc[i,13] = 'sixties' 
    elif (df5.iloc[i,8] >= datetime.date(1900, 1, 1) and df5.iloc[i,8] < datetime.date(1960, 1, 1)):
        df5.iloc[i,13] = 'early1900s'
    elif (df5.iloc[i,8] < datetime.date(1900, 1, 1) and df5.iloc[i,8] >= datetime.date(1600, 1, 1)):
        df5.iloc[i,13] = 'modern'
    elif (df5.iloc[i,8] < datetime.date(1600, 1, 1)):
        df5.iloc[i,13] = 'pre-modern'

In [42]:
df3['dat_category'] = df3['publish_date'].copy()
for i in range(0, len(df3.publish_date)):
    if df3.iloc[i,8] > datetime.date(2018, 12, 31):
        df3.iloc[i,13] = 'hardcover only'
    elif (df3.iloc[i,8] <= datetime.date(2018, 12, 31) and df3.iloc[i,8] > datetime.date(2015, 1, 1)):
        df3.iloc[i,13] = 'within bookclub'
    elif (df3.iloc[i,8] <= datetime.date(2015, 1, 1) and df3.iloc[i,8] > datetime.date(2006, 8, 1)):
        df3.iloc[i,13] = 'college books'
    elif (df3.iloc[i,8] <= datetime.date(2006, 8, 1) and df3.iloc[i,8] >= datetime.date(2000, 1, 1)):
        df3.iloc[i,13] = 'early aughts'
    elif (df3.iloc[i,8] < datetime.date(2000, 1, 1) and df3.iloc[i,8] >= datetime.date(1990, 1, 1)):
        df3.iloc[i,13] = 'nineties' 
    elif (df3.iloc[i,8] < datetime.date(1990, 1, 1) and df3.iloc[i,8] >= datetime.date(1970, 1, 1)):
        df3.iloc[i,13] = 'seventies-eighties' 
    elif (df3.iloc[i,8] < datetime.date(1970, 1, 1) and df3.iloc[i,8] >= datetime.date(1960, 1, 1)):
        df3.iloc[i,13] = 'sixties' 
    elif (df3.iloc[i,8] >= datetime.date(1900, 1, 1) and df3.iloc[i,8] < datetime.date(1960, 1, 1)):
        df3.iloc[i,13] = 'early1900s'
    elif (df3.iloc[i,8] < datetime.date(1900, 1, 1) and df3.iloc[i,8] >= datetime.date(1600, 1, 1)):
        df3.iloc[i,13] = 'modern'
    elif (df3.iloc[i,8] < datetime.date(1600, 1, 1)):
        df3.iloc[i,13] = 'pre-modern'

In [43]:
df5.columns

Index(['book_average_rating', 'author_gender', 'author_genres',
       'author_average_rating', 'Title', 'genre_1', 'genre_2', 'pages',
       'publish_date', 'Author', 'Genre1_Stemmed', 'Genre2_Stemmed',
       'authorgenre_stemmed', 'dat_category'],
      dtype='object')

In [44]:
table1 = df5[['Genre1_Stemmed','Title']].groupby('Genre1_Stemmed').count()
table1.sort_values(by='Title', ascending =False)

                 Title
Genre1_Stemmed
fiction             30
nonfict              7
histor               4
fantasi              3
science fict         2
short stori          2
autobiographi        1
classic              1
histori              1
historical fict      1
mysteri              1

In [45]:
table1 = df5[['Genre2_Stemmed','Title']].groupby('Genre2_Stemmed').count()
table1.sort_values(by='Title', ascending =False)

                  Title
Genre2_Stemmed
fiction              13
historical fict       5
classic               4
contemporari          4
histor                4
autobiographi         4
science fict          3
mysteri               3
cultur                2
magical r             1
short stori           1
nonfict               1
non-fict              1
african american      1
humor                 1
horror                1
histori               1
food and drink        1
dystopia              1
thriller              1

In [46]:
table1 = df5[['Title', 'dat_category']].groupby('dat_category').count()
table1.sort_values(by='Title', ascending =False)

                    Title
dat_category
college books          23
within bookclub         9
early aughts            8
nineties                5
seventies-eighties      4
early1900s              2
modern                  1
sixties                 1

In [47]:
table = df3[['Title', 'dat_category']].groupby('dat_category').count()
table.sort_values(by='Title', ascending =False)

                    Title
dat_category
college books        8459
within bookclub      2433
early aughts         1515
nineties             1115
seventies-eighties   1088
early1900s            696
hardcover only        434
sixties               278
modern                272
pre-modern             74

In [48]:
df5.sort_values(by = 'book_average_rating', ascending = False)

,book_average_rating,author_gender,author_genres,author_average_rating,Title,genre_1,genre_2,pages,publish_date,Author,Genre1_Stemmed,Genre2_Stemmed,authorgenre_stemmed,dat_category
17,5.00,male,literature-fiction,4.31,All the Light We Cannot See,Historical,Fiction,531,2014-07-08,Anthony Doerr,histor,fiction,literature-fict,college books
47,5.00,female,historical-fiction,4.32,Circe,Fantasy,Fiction,393,2018-07-08,Madeline Miller,fantasi,fiction,historical-fict,within bookclub
7,5.00,male,literature-fiction,4.13,Constellation of Vital Phenomena,fiction,historical fiction,416,2014-02-04,Anthony Marra,fiction,historical fict,literature-fict,college books
31,5.00,female,fiction,3.93,The Goldfinch,Fiction,Contemporary,771,2013-09-23,Donna Tartt,fiction,contemporari,fiction,college books
27,5.00,female,fiction,3.50,The Flamethrowers,Fiction,Historical,383,2013-07-08,Rachel Kushner,fiction,histor,fiction,college books
22,5.00,female,literature-fiction,4.01,Station Eleven,Fiction,Science Fiction,336,2014-07-08,Emily St John Mandel,fiction,science fict,literature-fict,college books
0,4.00,female,literature-fiction,4.14,Interpreter of Maladies,Short Stories,Fiction,198,1999-04-20,Jhumpa Lahiri,short stori,fiction,literature-fict,nineties
43,4.00,male,cooking-food-wine,3.97,Kitchen Confidential: Adventures in the Culina...,Nonfiction,Food and Drink,312,2000-05-22,Anthony Bourdain,nonfict,food and drink,cooking-food-win,early aughts
4,4.00,male,literature-fiction,3.81,Transatlantic,fiction,historical fiction,304,2013-06-04,Colum McCann,fiction,historical fict,literature-fict,college books
41,4.00,female,literature-fiction,3.93,Where I was from,nonfiction,autobiography,240,2004-09-14,Joan Didion,nonfict,autobiographi,literature-fict,early aughts
28,4.00,female,literature-fiction,3.90,The Round House,fiction,mystery,323,2012-10-02,Louise Erdrich,fiction,mysteri,literature-fict,college books
11,4.00,female,literature-fiction,4.01,The Lowland,Fiction,Cultural,340,2013-07-08,Jhumpa Lahiri,fiction,cultur,literature-fict,college books
23,4.00,female,literature-fiction,3.64,The Turner House,fiction,african american,341,2015-04-14,Angela Flournoy,fiction,african american,literature-fict,within bookclub
35,3.90,female,literature-fiction,4.00,The Blind Assassin,Fiction,Historical,521,2000-09-02,Margaret Atwood,fiction,histor,literature-fict,early aughts
1,3.90,male,memior,4.08,One Summer,History,Non-fiction,456,2013-10-01,Bill Bryson,histori,non-fict,memior,college books
15,3.90,male,history,4.34,The Boys in the Boat: Nine Americans and Their...,Nonfiction,History,416,2013-07-08,Daniel James Brown,nonfict,histori,histori,college books
52,3.80,female,literature-fiction,4.02,News of the World,Historical,Fiction,209,2016-03-29,Paulette Jiles,histor,fiction,literature-fict,within bookclub
51,3.78,male,literature-fiction,3.64,The Family Fang,fiction,humor,320,2011-08-01,Kevin Wilson,fiction,humor,literature-fict,college books
18,3.60,female,literature-fiction,4.00,The Lacuna,Fiction,Historical,508,2009-07-08,Barbara Kingsolver,fiction,histor,literature-fict,college books
44,3.50,female,literature-fiction,3.90,The Future Home of the Living God,fiction,dystopia,263,2017-11-14,Louise Erdrich,fiction,dystopia,literature-fict,within bookclub
3,3.50,male,nonfiction,3.62,Reading Lolita in Tehran: A Memoir in Books,Nonfiction,Autobiography,356,2003-03-25,Azar Nafisi,nonfict,autobiographi,nonfict,early aughts
24,3.50,male,literature-fiction,4.01,The Unbearable Lightness of Being,Fiction,Classics,320,1984-07-08,Milan Kundera,fiction,classic,literature-fict,seventies-eighties
25,3.50,male,biographies-memoirs,4.02,The Good Lord Bird,Historical,Fiction,417,2013-07-08,James McBride,histor,fiction,biographies-memoir,college books
34,3.50,female,nonfiction,4.13,The Distance Between Us,nonfiction,autobiography,336,2012-04-28,Reyna Grande,nonfict,autobiographi,nonfict,college books
16,3.00,male,fiction,3.92,Runaway,Short Stories,Fiction,335,2003-08-11,Alice Munro,short stori,fiction,fiction,early aughts
30,3.00,male,literature-fiction,3.57,The Buddha of Suburbia,Fiction,Contemporary,288,1990-07-08,Hanif Kureishi,fiction,contemporari,literature-fict,nineties
45,3.00,female,fiction,3.64,Wide Sargasso Sea,Fiction,Classics,160,1966-07-08,Jean Rhys,fiction,classic,fiction,sixties
39,3.00,female,poetry,3.92,Lit,Autobiography,Nonfiction,400,2009-07-08,Mary Karr,autobiographi,nonfict,poetri,college books
33,3.00,male,fiction,3.80,Did You Ever Have a Family,Fiction,Contemporary,293,2015-07-08,Bill Clegg,fiction,contemporari,fiction,within bookclub
26,3.00,male,non-fiction,4.34,When Breath Becomes Air,Nonfiction,Autobiography,208,2016-01-12,Paul Kalanithi,nonfict,autobiographi,non-fict,within bookclub
10,3.00,female,literature-fiction,3.81,The History of Love,Fiction,Historical,255,2005-05-17,Nicole Krauss,fiction,histor,literature-fict,early aughts
42,2.90,female,literature-fiction,3.70,Caramelo,fiction,historical fiction,441,2003-09-09,Sandra Cisneros,fiction,historical fict,literature-fict,early aughts
19,2.90,male,literature-fiction,4.20,Ready Player One,science fiction,fiction,374,2011-08-16,Ernest Cline,science fict,fiction,literature-fict,college books
46,2.90,female,science-fiction-fantasy,4.08,The Sparrow,Science Fiction,Fiction,431,1996-07-08,Mary Doria Russell,science fict,fiction,science-fiction-fantasi,nineties
20,2.90,female,fiction,3.98,Big Little Lies,Fiction,Mystery,460,2014-07-08,Liane Moriarty,fiction,mysteri,fiction,college books
49,2.75,female,fiction,3.95,Behold the Dreamers,Fiction,Cultural,400,2016-03-15,Imbolo Mbue,fiction,cultur,fiction,within bookclub
2,2.50,male,literature-fiction,4.16,A River Runs Through it and Other Stories,Fiction,Short Stories,217,1976-07-08,Norman Maclean,fiction,short stori,literature-fict,seventies-eighties
37,2.50,female,fiction,3.84,Z: a novel of Zelda Fitzgerald,historical fiction,fiction,464,2013-03-26,Therese Anne Fowler,historical fict,fiction,fiction,college books
5,2.00,male,literature-fiction,3.83,Fight Club,Fiction,Contemporary,218,1996-07-08,Chuck Palahniuk,fiction,contemporari,literature-fict,nineties
9,2.00,male,biographies-memoirs,3.71,The Circle,Fiction,Science Fiction,493,2013-07-08,Dave Eggers,fiction,science fict,biographies-memoir,college books
8,2.00,male,literature-fiction,3.90,Lexicon,fiction,science fiction,390,2013-06-08,Max Berry,fiction,science fict,literature-fict,college books
21,1.90,female,literature-fiction,4.04,The Night Circus,Fantasy,Fiction,387,2011-07-08,Erin Morgenstern,fantasi,fiction,literature-fict,college books
29,1.00,female,literature-fiction,3.60,The Shining Girls,Fiction,Mystery,368,2013-07-08,Lauren Beukes,fiction,mysteri,literature-fict,college books
38,1.00,male,literature-fiction,3.93,The Underground Railroad,Historical,Fiction,306,2016-07-08,Colson Whitehead,histor,fiction,literature-fict,within bookclub
14,0.00,female,literature-fiction,3.96,Geek Love,Fiction,Horror,348,1989-03-08,Katherine Dunn,fiction,horror,literature-fict,seventies-eighties
40,0.00,male,literature-fiction,3.91,Fathers and Sons,Classics,Fiction,244,1862-02-08,Ivan Turgenev,classic,fiction,literature-fict,modern
13,0.00,female,literature-fiction,3.51,As She Left It,Mystery,Thriller,343,2013-06-08,Catriona Mcpherson,mysteri,thriller,literature-fict,college books
36,0.00,male,literature-fiction,3.77,Exit West,Fiction,Magical Realism,231,2017-03-02,Mohsin Hamid,fiction,magical r,literature-fict,within bookclub
48,0.00,male,literature-fiction,3.64,Balzac and the Little Chinese Seamstress,fiction,historical fiction,184,2002-10-29,Dai Sijie,fiction,historical fict,literature-fict,early aughts
12,0.00,male,literature-fiction,3.69,Quarantine,fiction,historical fiction,256,1997-06-01,Jim Crace,fiction,historical fict,literature-fict,nineties
50,0.00,male,horror,4.03,The Gunslinger,fantasy,fiction,231,1982-06-01,Stephen King,fantasi,fiction,horror,seventies-eighties
32,0.00,male,"fiction,poetry",3.97,Independent People,Fiction,Classics,482,1934-07-08,Halld r Kiljan Laxness,fiction,classic,"fiction,poetri",early1900s
6,0.00,male,literature-fiction,3.84,The Log from The Sea of Cortez,nonfiction,classics,288,1951-01-01,John Steinbeck,nonfict,classic,literature-fict,early1900s

In [49]:
df3.columns

Index(['author_average_rating', 'author_gender', 'author_genres',
       'book_average_rating', 'Title', 'genre_1', 'genre_2', 'pages',
       'publish_date', 'Author', 'Genre1_Stemmed', 'Genre2_Stemmed',
       'authorgenre_stemmed', 'dat_category'],
      dtype='object')

In [50]:
df3 = df3.loc[df3['pages'] != '1 page']
df3['pages'] = pd.to_numeric(df3['pages'])

In [51]:
df5['pages'] = pd.to_numeric(df5['pages'])

In [52]:
df5.shape

(53, 14)

In [53]:
df3 = df3.append(df5)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [54]:
training = pd.get_dummies(df3[['author_gender', 'author_genres', 
        'Genre1_Stemmed', 'Genre2_Stemmed',
       'authorgenre_stemmed', 'dat_category']])

In [55]:
training['author_average_rating']= df3['author_average_rating'].copy()
training['book_average_rating']= df3['book_average_rating'].copy()
training['pages'] = df3['pages'].copy()
training['Title'] = df3['Title'].copy()
training = training.set_index('Title')

In [56]:
bookclub = training.iloc[16362:16415,:].copy()
bookclub.tail()

,author_gender_female,author_gender_male,author_genres_action,author_genres_action-adventure,author_genres_adult,author_genres_adult-new-adult-young-adult,author_genres_adventure,"author_genres_adventure,romance",author_genres_african-american-studies,author_genres_alcoholism-recovery,...,dat_category_hardcover only,dat_category_modern,dat_category_nineties,dat_category_pre-modern,dat_category_seventies-eighties,dat_category_sixties,dat_category_within bookclub,author_average_rating,book_average_rating,pages
Title,,,,,,,,,,,,,,,,,,,,,
Balzac and the Little Chinese Seamstress,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.64,0.00,184.0
Behold the Dreamers,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,3.95,2.75,400.0
The Gunslinger,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,4.03,0.00,231.0
The Family Fang,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.64,3.78,320.0
News of the World,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,4.02,3.80,209.0

In [57]:
training = training.drop(training.tail(53).index)
training.tail()

,author_gender_female,author_gender_male,author_genres_action,author_genres_action-adventure,author_genres_adult,author_genres_adult-new-adult-young-adult,author_genres_adventure,"author_genres_adventure,romance",author_genres_african-american-studies,author_genres_alcoholism-recovery,...,dat_category_hardcover only,dat_category_modern,dat_category_nineties,dat_category_pre-modern,dat_category_seventies-eighties,dat_category_sixties,dat_category_within bookclub,author_average_rating,book_average_rating,pages
Title,,,,,,,,,,,,,,,,,,,,,
Where the Wild Things Are,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,4.20,4.22,37.0
Allegiant,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.08,3.63,526.0
The Picture of Dorian Gray,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,4.09,4.07,367.0
Alice's Adventures in Wonderland & Through the Looking-Glass,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,4.06,4.07,239.0
The Giving Tree,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,4.33,4.37,64.0

In [58]:
from scipy.sparse import *
from scipy import *
training_matrix = csr_matrix(training.values)

In [59]:
from sklearn.neighbors import NearestNeighbors
trainingnp = training.values

model_knn = NearestNeighbors(metric='cosine', algorithm='brute')
model_knn.fit(training_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [60]:
bookclub

,author_gender_female,author_gender_male,author_genres_action,author_genres_action-adventure,author_genres_adult,author_genres_adult-new-adult-young-adult,author_genres_adventure,"author_genres_adventure,romance",author_genres_african-american-studies,author_genres_alcoholism-recovery,...,dat_category_hardcover only,dat_category_modern,dat_category_nineties,dat_category_pre-modern,dat_category_seventies-eighties,dat_category_sixties,dat_category_within bookclub,author_average_rating,book_average_rating,pages
Title,,,,,,,,,,,,,,,,,,,,,
Interpreter of Maladies,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,4.14,4.00,198.0
One Summer,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.08,3.90,456.0
A River Runs Through it and Other Stories,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,4.16,2.50,217.0
Reading Lolita in Tehran: A Memoir in Books,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.62,3.50,356.0
Transatlantic,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.81,4.00,304.0
Fight Club,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,3.83,2.00,218.0
The Log from The Sea of Cortez,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.84,0.00,288.0
Constellation of Vital Phenomena,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.13,5.00,416.0
Lexicon,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.90,2.00,390.0
The Circle,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.71,2.00,493.0
The History of Love,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.81,3.00,255.0
The Lowland,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.01,4.00,340.0
Quarantine,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,3.69,0.00,256.0
As She Left It,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.51,0.00,343.0
Geek Love,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,3.96,0.00,348.0
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.34,3.90,416.0
Runaway,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.92,3.00,335.0
All the Light We Cannot See,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.31,5.00,531.0
The Lacuna,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.00,3.60,508.0
Ready Player One,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.20,2.90,374.0
Big Little Lies,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.98,2.90,460.0
The Night Circus,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.04,1.90,387.0
Station Eleven,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.01,5.00,336.0
The Turner House,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,3.64,4.00,341.0
The Unbearable Lightness of Being,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,4.01,3.50,320.0
The Good Lord Bird,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.02,3.50,417.0
When Breath Becomes Air,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,4.34,3.00,208.0
The Flamethrowers,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.50,5.00,383.0
The Round House,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.90,4.00,323.0
The Shining Girls,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.60,1.00,368.0
The Buddha of Suburbia,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,3.57,3.00,288.0
The Goldfinch,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.93,5.00,771.0
Independent People,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.97,0.00,482.0
Did You Ever Have a Family,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,3.80,3.00,293.0
The Distance Between Us,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.13,3.50,336.0
The Blind Assassin,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4.00,3.90,521.0
Exit West,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,3.77,0.00,231.0
Z: a novel of Zelda Fitzgerald,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.84,2.50,464.0
The Underground Railroad,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,3.93,1.00,306.0
Lit,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.92,3.00,400.0
Fathers and Sons,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,3.91,0.00,244.0
Where I was from,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.93,4.00,240.0
Caramelo,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.70,2.90,441.0
Kitchen Confidential: Adventures in the Culinary Underbelly,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.97,4.00,312.0
The Future Home of the Living God,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,3.90,3.50,263.0
Wide Sargasso Sea,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,3.64,3.00,160.0
The Sparrow,1,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,4.08,2.90,431.0
Circe,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,4.32,5.00,393.0
Balzac and the Little Chinese Seamstress,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.64,0.00,184.0
Behold the Dreamers,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,3.95,2.75,400.0
The Gunslinger,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,4.03,0.00,231.0
The Family Fang,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.64,3.78,320.0
News of the World,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,4.02,3.80,209.0

In [61]:
bookclub.iloc[22,:]

author_gender_female                                                    1.00
author_gender_male                                                      0.00
author_genres_action                                                    0.00
author_genres_action-adventure                                          0.00
author_genres_adult                                                     0.00
author_genres_adult-new-adult-young-adult                               0.00
author_genres_adventure                                                 0.00
author_genres_adventure,romance                                         0.00
author_genres_african-american-studies                                  0.00
author_genres_alcoholism-recovery                                       0.00
author_genres_alternative-history                                       0.00
author_genres_amish                                                     0.00
author_genres_anthropology                                              0.00
author_genres_art                                                       0.00
author_genres_arts-photography                                          0.00
author_genres_arts-photography,children-s-books                         0.00
author_genres_autobiography                                             0.00
author_genres_bdsm                                                      0.00
author_genres_bdsm-erotica-erotic-romance                               0.00
author_genres_bdsm-romance                                              0.00
author_genres_biblical-fiction                                          0.00
author_genres_biographies-memoirs                                       0.00
author_genres_biographies-memoirs,diaries                               0.00
author_genres_biographies-memoirs,entertainment                         0.00
author_genres_biographies-memoirs,history                               0.00
author_genres_biographies-memoirs,literature-fiction                    0.00
author_genres_biographies-memoirs,nonfiction                            0.00
author_genres_biographies-memoirs,poetry                                0.00
author_genres_biographies-memoirs,politics                              0.00
author_genres_biography                                                 0.00
                                                                       ...
authorgenre_stemmed_young-adult,histori                                 0.00
authorgenre_stemmed_young-adult,horror                                  0.00
authorgenre_stemmed_young-adult,humor-and-comedi                        0.00
authorgenre_stemmed_young-adult,literature-fict                         0.00
authorgenre_stemmed_young-adult,nonfict                                 0.00
authorgenre_stemmed_young-adult,paranorm                                0.00
authorgenre_stemmed_young-adult,rom                                     0.00
authorgenre_stemmed_young-adult,science-fict                            0.00
authorgenre_stemmed_young-adult,science-fiction-fantasi                 0.00
authorgenre_stemmed_young-adult,suspens                                 0.00
authorgenre_stemmed_young-adult-book                                    0.00
authorgenre_stemmed_young-adult-new-adult                               0.00
authorgenre_stemmed_young-adult-new-adult-adult                         0.00
authorgenre_stemmed_young-adult-paranormal-fantasi                      0.00
authorgenre_stemmed_young-adult-paranormal-rom                          0.00
authorgenre_stemmed_young-adult-paranormal-romance,paranormal-fict      0.00
authorgenre_stemmed_yuri                                                0.00
dat_category_college books                                              1.00
dat_category_early aughts                                               0.00
dat_category_early1900s                                                 0.00
dat_category_hardcover only                                             0.00
dat_category_modern                                                     0.00
dat_category_nineties                                                   0.00
dat_category_pre-modern                                                 0.00
dat_category_seventies-eighties                                         0.00
dat_category_sixties                                                    0.00
dat_category_within bookclub                                            0.00
author_average_rating                                                   4.01
book_average_rating                                                     5.00
pages                                                                 336.00
Name: Station Eleven, Length: 1612, dtype: float64

In [62]:
df3.loc[df3.Title == 'A Stop in the Park']

,Author,Genre1_Stemmed,Genre2_Stemmed,Title,author_average_rating,author_gender,author_genres,authorgenre_stemmed,book_average_rating,dat_category,genre_1,genre_2,pages,publish_date
2372,Peggy Morehouse Strack,fiction,contemporari,A Stop in the Park,4.02,male,literature-fiction,literature-fict,4.02,college books,Fiction,Contemporary,366.0,2012-09-09

In [63]:
query_index = 7
distances, indicies = model_knn.kneighbors(np.array(bookclub.iloc[query_index, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(bookclub.index[query_index]))
    else:
        
        print('{0}'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for Constellation of Vital Phenomena:

A Stop in the Park

A Thousand Splendid Suns

And the Mountains Echoed

Tell the Wolves I'm Home

The Crying Tree

In [64]:
query_index = 31
distances, indicies = model_knn.kneighbors(np.array(bookclub.iloc[query_index, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(bookclub.index[query_index]))
    else:
        
        print('{0}:'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for The Goldfinch:

A Brief History of Seven Killings:

The Corrections:

The Way the Crow Flies:

The Golden Notebook:

The Emperor Waltz:

In [65]:
query_index = 32
distances, indicies = model_knn.kneighbors(np.array(bookclub.iloc[query_index, :]).reshape(1,-1), n_neighbors = 5)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(bookclub.index[query_index]))
    else:
        
        print('{0}:'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for Independent People:

Dianetics: The Modern Science of Mental Health:

The Good Soldier Švejk:

Don Quixote:

The 120 Days of Sodom and Other Writings:

In [66]:
df5.tail(1)

,book_average_rating,author_gender,author_genres,author_average_rating,Title,genre_1,genre_2,pages,publish_date,Author,Genre1_Stemmed,Genre2_Stemmed,authorgenre_stemmed,dat_category
52,3.8,female,literature-fiction,4.02,News of the World,Historical,Fiction,209.0,2016-03-29,Paulette Jiles,histor,fiction,literature-fict,within bookclub

In [67]:
query_index = 6
distances, indicies = model_knn.kneighbors(np.array(bookclub.iloc[query_index, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(bookclub.index[query_index]))
    else:
        
        print('{0}:'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for The Log from The Sea of Cortez:

Aşk-ı Memnu:

The Ragged Trousered Philanthropists:

Two Lives:

Look Homeward, Angel:

The Tin Drum:

In [68]:
query_index = 50
distances, indicies = model_knn.kneighbors(np.array(bookclub.iloc[query_index, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(bookclub.index[query_index]))
    else:
        
        print('{0}:'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for The Gunslinger:

Flesh:

Cabal:

Smog City:

Dark Winter: The Wicca Circle:

H.P. Lovecraft's Book of the Supernatural: Classic Tales of the Macabre:

In [69]:
df5.loc[df5.Title == "All the Light We Cannot See"]

,book_average_rating,author_gender,author_genres,author_average_rating,Title,genre_1,genre_2,pages,publish_date,Author,Genre1_Stemmed,Genre2_Stemmed,authorgenre_stemmed,dat_category
17,5.0,male,literature-fiction,4.31,All the Light We Cannot See,Historical,Fiction,531.0,2014-07-08,Anthony Doerr,histor,fiction,literature-fict,college books

In [70]:
query_index = 47
distances, indicies = model_knn.kneighbors(np.array(bookclub.iloc[query_index, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(bookclub.index[query_index]))
    else:
        
        print('{0}:'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for Circe:

Apricots and Wolfsbane:

A Different Kind of Fire:

The Green Phoenix: A Novel of the Woman Who Re-Made Asia, Empress Xiaozhuang:

We Were the Lucky Ones:

The Fire by Night:

In [71]:
pick_number = 41
distances, indicies = model_knn.kneighbors(np.array(bookclub.iloc[pick_number, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(bookclub.index[pick_number]))
    else:
        
        print('{0}:'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for Where I was from:

Why Be Happy When You Could Be Normal?:

The Princess Diarist:

Wild: From Lost to Found on the Pacific Crest Trail:

It's My Life:

Saving Francesca:

In [72]:
query_index = 22
distances, indicies = model_knn.kneighbors(np.array(bookclub.iloc[query_index, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(bookclub.index[query_index]))
    else:
        
        print('{0}:'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for Station Eleven:

A Dog's Purpose:

Room:

Whistling Past the Graveyard:

Garden Spells:

All My Puny Sorrows:

In [73]:

moms_pick1 = training.loc[training.index == "Gilead"].copy()
moms_pick1 = moms_pick1.append(training.loc[training.index == "Housekeeping"]).copy()

In [74]:
training = training.loc[training.index != "Gilead"]
training = training.loc[training.index != "Housekeeping"]

In [75]:
moms_pick1.head()

,author_gender_female,author_gender_male,author_genres_action,author_genres_action-adventure,author_genres_adult,author_genres_adult-new-adult-young-adult,author_genres_adventure,"author_genres_adventure,romance",author_genres_african-american-studies,author_genres_alcoholism-recovery,...,dat_category_hardcover only,dat_category_modern,dat_category_nineties,dat_category_pre-modern,dat_category_seventies-eighties,dat_category_sixties,dat_category_within bookclub,author_average_rating,book_average_rating,pages
Title,,,,,,,,,,,,,,,,,,,,,
Gilead,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3.87,3.85,247.0
Housekeeping,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,3.87,3.82,219.0

In [76]:
from sklearn.neighbors import NearestNeighbors
trainingnp = training.values

model_knn = NearestNeighbors(metric='cosine', algorithm='brute')
model_knn.fit(training_matrix)

NearestNeighbors(algorithm='brute', leaf_size=30, metric='cosine',
         metric_params=None, n_jobs=None, n_neighbors=5, p=2, radius=1.0)

In [78]:
query_index = 0
distances, indicies = model_knn.kneighbors(np.array(moms_pick1.iloc[query_index, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(moms_pick1.index[query_index]))
    else:
        
        print('{0}'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for Gilead:

Hate List

Who She Is

A New Earth: Awakening to Your Life's Purpose

Take Me, Break Me

How to Be an American Housewife

In [79]:
query_index = 1
distances, indicies = model_knn.kneighbors(np.array(moms_pick1.iloc[query_index, :]).reshape(1,-1), n_neighbors = 6)

for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(moms_pick1.index[query_index]))
    else:
        
        print('{0}'.format(training.index[indicies.flatten()[i]], distances.flatten()))
        print()

Recommendations for Housekeeping:

The Sorrow Of War: A Novel of North Vietnam

Fifth Business

زندگی در پیش رو

നക്ഷത്രങ്ങളേ കാവല്‍ | Nakshathrangale Kaval

Factotum

# convert word doc to csv

Interpreter of Maladies,Jhumpa Lahiri,Chris
One Summer,Bill Bryson,Schmidt
A River Runs Through It,Norman Maclean,Eric
Reading Lolita in Tehran,Azar Nafisi,Emily 
Transatlantic,Colum McCann,David
Fight Club,Chuck Palahniuk,Schmidt
The Log from The Sea of Cortez,John Steinbeck,Eric
Constellation of Vital Phenomena,Anthony Marra,Chris
Lexicon,Max Berry,Emily
The Circle,Dave Eggers,Chris
History of Love,Nicole Krauss,Megan
The Lowland,Jhumpa Lahiri,Emily
Quarantine,Jim Crace,David
As She Left It,Catriona Mcpherson,Eric
Geek Love,Katharine Dunn,Adam
The Boys in the Boa,Daniel James Brown,Megan
Runaway,Alice Munro,David 
All The Light We Cannot See,Anthony Doerr, Group
The Lacuna,Barbara Kingsolver,Emily
Ready Player One,Ernest Cline,Eric 
Big Little Lies,Liane Moriarty,Megan 
The Night Circus,Erin Morgenstern, Candace
Station Eleven,Hilary Saint Mandel,David 
The Turner House,Angela Fournoy,Kate 
The Unbearable lightness of being,Milan Kundera, Tony
The Good Lord Bird,James McBride,Emily 
When Breath Becomes Air,Paul Kalanthi,Eric
The Flamethrowers,Rachel Kushner,Megan 
The Round House,Louise Erhlic,David
The Shining Girls,Lauren Beukes,Kate
The Buddha of Suburbia,Hanif Kureishi,Tony
The Goldfinch,Donna Tart,Emily
Independent People,Haldor Laxness,Eric,
Did You Ever Have A Family,Bill Clegg,Megan,
The Distance Between Us,Reyna Grande,David
The Blind Assassin,Margaret Atwood,Kate 
Exit West,Mohsin Hamid,Tony
Z: a novel of Zelda Fitzgerald,Therese Anne Fowler,Emily
The Underground Railroad,Colson Whitehead,Eric
Lit: A memoir, Mary Karr, Megan 
Fathers and Sons,Ivan Turgenev,David
Where I was from,Joan Didion,Kate
Caramelo,Sandra Cisneros,Tony 
Kitchen Confidential,Anthony Bourdain,Emily
The Future Home of the Living God,Louise Erdrich, Eric
Wide Sargasso Sea,Jean Rhys,Megan 
The Sparrow , Mary Doria Russell, David
Circe, Madeline Miller Kate 
Balzac and the Little Chinese Seamstress, Dai Sijie, Tony
Behold the Dreamers, Imbolo Mbue, Emily 
The Gunslinger, Stephen King,Eric
The Family Fang,Kevin Wilson,Megan
News of the World,Paulette Jiles,David